VehicleRentalSystem/Models/Branch.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace VehicleRentalSystem.Models
{
    public class Branch
    {
        [Display(Name = "Id")]
        public int BusinessEntityId { get; set; }
        [Display(Name = "Branch Name")]
        public string Name { get; set; }
        public BusinessEntity BusinessEntity { get; set; }

        public ICollection<Customer> Customers { get; set; }
        public ICollection<Vehicle> Vehicles{ get; set; }
    }
}

VehicleRentalSystem/Models/ManageViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;

namespace VehicleRentalSystem.Models
{
    public class IndexViewModel
    {
        public bool HasPassword { get; set; }
        public IList<UserLoginInfo> Logins { get; set; }
        public string PhoneNumber { get; set; }
        public bool TwoFactor { get; set; }
        public bool BrowserRemembered { get; set; }
    }

    public class ManageLoginsViewModel
    {
        public IList<UserLoginInfo> CurrentLogins { get; set; }
        public IList<AuthenticationDescription> OtherLogins { get; set; }
    }

    public class FactorViewModel
    {
        public string Purpose { get; set; }
    }

    public class SetPasswordViewModel
    {
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ChangePasswordViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class AddPhoneNumberViewModel
    {
        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string Number { get; set; }
    }

    public class VerifyPhoneNumberViewModel
    {
        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; }

        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
    }

    public class ConfigureTwoFactorViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
    }
}

VehicleRentalSystem/ViewModels/BranchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using VehicleRentalSystem.Models;

namespace VehicleRentalSystem.ViewModels
{
    public class BranchViewModel
    {
        public Branch Branch { get; set; }
        public Address Address { get; set; }
    }
}

VehicleRentalSystem/Controllers/BranchController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VehicleRentalSystem.DTOs;
using VehicleRentalSystem.Models;
using VehicleRentalSystem.ViewModels;

namespace VehicleRentalSystem.Controllers
{
    public class BranchController : Controller
    {
        [Route("Branches")]
        public ActionResult Manage()
        {
            return View();
        }

       
        public ActionResult AddOrEdit(int id = 0)
        {
            using(ApplicationDbContext db = new ApplicationDbContext())
            {
                if (id == 0)
                {
                    return View();                  
                }
                else
                {
                    BranchViewModel viewModel = new BranchViewModel
                    {
                        Branch = db.Branches.Find(id),
                        Address = db.Addresses.Find(db.BusinessEntityAddresses.Where(b => b.BusinessEntityId == id && b.AddressTypeId == 2).Single().AddressId)
                    };

                    return View(viewModel);                   
                }
            }
        }

        [HttpPost]
        public ActionResult AddOrEdit(BranchViewModel newBranch)
        {
            using (ApplicationDbContext db = new ApplicationDbContext())
            {              
                if (db.Branches.Any(x => x.BusinessEntityId == newBranch.Branch.BusinessEntityId))
                {
                    db.Branches.Attach(newBranch.Branch);
                    db.Entry(newBranch.Branch).State = EntityState.Modified;


                    db.Addresses.Attach(newBranch.Address);
                    db.Entry(newBranch.Address).State = EntityState.Modified;

                    db.SaveChanges();

                    return Json(new { success = true, message = "Updated Successfully" }, JsonRequestBehavior.AllowGet);

                }
                else
                {
                    BusinessEntity be = new BusinessEntity();
                    db.BusinessEntities.Add(be);
                    newBranch.Branch.BusinessEntity = be;

                    db.Branches.Add(newBranch.Branch);
                    db.Addresses.Add(newBranch.Address);


                    BusinessEntityAddress bea = new BusinessEntityAddress {
                        BusinessEntity = be,
                        AddressType = db.AddressesTypes.Find(2),
                        Address = newBranch.Address
                    };

                    db.BusinessEntityAddresses.Add(bea);
                    db.SaveChanges();
                    return Json(new { success = true, message = "Saved Successfully" }, JsonRequestBehavior.AllowGet);
                }
            }
        }

        [HttpGet]
        public ActionResult GetData()
        {
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                // create DTO with Branch and Branch Address data
                var data2 = db.Branches
                    .Join(
                        db.BusinessEntityAddresses,
                        branch => branch.BusinessEntityId,
                        bea => bea.BusinessEntityId,
                        (branch, bea) => new BranchDTO
                        {
                            Id = branch.BusinessEntityId,
                            Name = branch.Name,
                            AddressLine1 = bea.Address.AddressLine1,
                            AddressLine2 = bea.Address.AddressLine2,
                            City = bea.Address.City,
                            PostalCode = bea.Address.PostalCode
                        }

                    ).ToList();

                return Json(new { data = data2 }, JsonRequestBehavior.AllowGet); // sent json of rentals to page
            }
        }

        public ActionResult Details(int? id)
        {
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                BranchViewModel viewModel = new BranchViewModel
                {
                    Branch = db.Branches.Find(id),
                    Address = db.Addresses.Find(db.BusinessEntityAddresses.Where(b => b.BusinessEntityId == id && b.AddressTypeId == 2).Single().AddressId)
                };

                return View(viewModel);
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                BusinessEntity be = db.BusinessEntities.Find(id);
                var addresses = db.BusinessEntityAddresses.Where(b => b.BusinessEntityId == id).Select(b => b.Address);

                db.BusinessEntities.Remove(be);                
                db.Addresses.RemoveRange(addresses);
                db.SaveChanges();
                return Json(new { success = true, message = "Deleted Successfully" }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

VehicleRentalSystem/Controllers/BranchesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VehicleRentalSystem.DTOs;
using VehicleRentalSystem.Models;
using VehicleRentalSystem.ViewModels;

namespace VehicleRentalSystem.Controllers
{
    public class BranchesController : Controller
    {
        [Route("Branches")]
        public ActionResult Manage()
        {
            return View();
        }

       
        public ActionResult AddOrEdit(int id = 0)
        {
            using(ApplicationDbContext db = new ApplicationDbContext())
            {
                if (id == 0)
                {
                    return View();                  
                }
                else
                {
                    BranchViewModel viewModel = new BranchViewModel
                    {
                        Branch = db.Branches.Find(id),
                        Address = db.Addresses.Find(db.BusinessEntityAddresses.Where(b => b.BusinessEntityId == id && b.AddressTypeId == 2).Single().AddressId)
                    };

                    return View(viewModel);                   
                }
            }
        }

        [HttpPost]
        public ActionResult AddOrEdit(BranchViewModel newBranch)
        {
            using (ApplicationDbContext db = new ApplicationDbContext())
            {              
                if (db.Branches.Any(x => x.BusinessEntityId == newBranch.Branch.BusinessEntityId))
                {
                    db.Branches.Attach(newBranch.Branch);
                    db.Entry(newBranch.Branch).State = EntityState.Modified;


                    db.Addresses.Attach(newBranch.Address);
                    db.Entry(newBranch.Address).State = EntityState.Modified;

                    db.SaveChanges();

                    return Json(new { success = true, message = "Updated Successfully" }, JsonRequestBehavior.AllowGet);

                }
                else
                {
                    BusinessEntity be = new BusinessEntity();
                    db.BusinessEntities.Add(be);
                    newBranch.Branch.BusinessEntity = be;

                    db.Branches.Add(newBranch.Branch);
                    db.Addresses.Add(newBranch.Address);


                    BusinessEntityAddress bea = new BusinessEntityAddress {
                        BusinessEntity = be,
                        AddressType = db.AddressesTypes.Find(2),
                        Address = newBranch.Address
                    };

                    db.BusinessEntityAddresses.Add(bea);
                    db.SaveChanges();
                    return Json(new { success = true, message = "Saved Successfully" }, JsonRequestBehavior.AllowGet);
                }
            }
        }

        [HttpGet]
        public ActionResult GetData()
        {
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                // create DTO with Branch and Branch Address data
                var data2 = db.Branches
                    .Join(
                        db.BusinessEntityAddresses,
                        branch => branch.BusinessEntityId,
                        bea => bea.BusinessEntityId,
                        (branch, bea) => new BranchDTO
                        {
                            Id = branch.BusinessEntityId,
                            Name = branch.Name,
                            AddressLine1 = bea.Address.AddressLine1,
                            AddressLine2 = bea.Address.AddressLine2,
                            City = bea.Address.City,
                            PostalCode = bea.Address.PostalCode
                        }

                    ).ToList();

                return Json(new { data = data2 }, JsonRequestBehavior.AllowGet); // sent json of rentals to page
            }
        }

        public ActionResult Details(int? id)
        {
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                BranchViewModel viewModel = new BranchViewModel
                {
                    Branch = db.Branches.Find(id),
                    Address = db.Addresses.Find(db.BusinessEntityAddresses.Where(b => b.BusinessEntityId == id && b.AddressTypeId == 2).Single().AddressId)
                };

                return View(viewModel);
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                BusinessEntity be = db.BusinessEntities.Find(id);
                var addresses = db.BusinessEntityAddresses.Where(b => b.BusinessEntityId == id).Select(b => b.Address);

                db.BusinessEntities.Remove(be);                
                db.Addresses.RemoveRange(addresses);
                db.SaveChanges();
                return Json(new { success = true, message = "Deleted Successfully" }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

VehicleRentalSystem/Views/Branch/AddOrEdit.cshtml
@model VehicleRentalSystem.ViewModels.BranchViewModel
@{
    Layout = null;
}
<!-- Branch Modal -->
<div class="modal fade" id="addOrEditModal" tabindex="-1" role="dialog" aria-labelledby="branchModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-gradient-primary">
                <h5 class="modal-title text-light" id="addOrEditModalLabel">Add New Branch</h5>
                <button id="close" class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <!-- Branch Form -->
            <div id="mbody" class="modal-body" style="padding-bottom:0px">

                @using (Html.BeginForm("AddOrEdit", "Branch", FormMethod.Post, new { onsubmit = "return SubmitForm(this)", @class = "form-horizontal", id = "add" }))
                {
                    <div class="container">
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Branch.BusinessEntityId)
                        @Html.HiddenFor(model => model.Address.AddressId)

                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-4 text-right font-weight-bold">
                                    @Html.LabelFor(model => model.Branch.Name, htmlAttributes: new { @class = "control-label" })
                                </div>
                                <div class="col-sm-8 text-left">
                                    @Html.EditorFor(model => model.Branch.Name, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                                    @Html.ValidationMessageFor(model => model.Branch.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-4 text-right font-weight-bold">
                                    @Html.LabelFor(model => model.Address.AddressLine1, htmlAttributes: new { @class = "control-label" })
                                </div>
                                <div class="col-sm-8 text-left">
                                    @Html.EditorFor(model => model.Address.AddressLine1, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                                    @Html.ValidationMessageFor(model => model.Address.AddressLine1, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-4 text-right font-weight-bold">
                                    @Html.LabelFor(model => model.Address.AddressLine2, htmlAttributes: new { @class = "control-label" })
                                </div>
                                <div class="col-sm-8 text-left">
                                    @Html.EditorFor(model => model.Address.AddressLine2, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                                    @Html.ValidationMessageFor(model => model.Address.AddressLine2, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-4 text-right font-weight-bold">
                                    @Html.LabelFor(model => model.Address.City, htmlAttributes: new { @class = "control-label" })
                                </div>
                                <div class="col-sm-8 text-left">
                                    @Html.EditorFor(model => model.Address.City, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                                    @Html.ValidationMessageFor(model => model.Address.City, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-4 text-right font-weight-bold">
                                    @Html.LabelFor(model => model.Address.PostalCode, htmlAttributes: new { @class = "control-label" })
                                </div>
                                <div class="col-sm-8 text-left">
                                    @Html.EditorFor(model => model.Address.PostalCode, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                                    @Html.ValidationMessageFor(model => model.Address.PostalCode, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="col-12 text-right align-content-center">
                            <div class="modal-footer border-0">
                                <input type="Reset" value="Reset" class="btn btn-secondary" />
                                <input type="submit" value="Submit" class="btn btn-primary" />
                            </div>

                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
</div>

VehicleRentalSystem/Views/Branch/Manage.cshtml
@model IEnumerable<VehicleRentalSystem.ViewModels.BranchViewModel>


<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h4 class="m-0 font-weight-bold text-primary text-center">Manage Branches</h4>

    </div>
    <!-- Branch Data Table Headings-->
    <div class="card-body">
        <div class="table-responsive">
            <a onclick="Add('@Url.Action("AddOrEdit", "Branch")')" class="btn btn-sm btn-primary btn-icon-split mb-4">
                <span class="icon text-white-50"><i class='fas fa-plus'></i></span>
                <span class="text text-white">Add</span>
            </a>
            <table id="branchTable" class="table table-bordered" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Branch.BusinessEntityId)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Branch.Name)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.Address.AddressLine1)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.Address.AddressLine2)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Address.City)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.Address.PostalCode)
                        </th>

                        <th>
                            Actions
                        </th>

                    </tr>
                </thead>

            </table>

        </div>
    </div>
</div>




@*containter for add and edit boostrap modals*@
<div id="modalContainer">

</div>

@*Delete rental Bootstrap modal*@
<div class="modal " id="delete" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-gradient-primary">
                <h5 class="modal-title text-light" id="deleteModalLabel">Delete Branch</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Are you sure you would like to delete this branch?</div>
            <div class="modal-footer border-0">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <button id="deleteButton" class="btn btn-primary" type="button">Delete</button>

            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script src="~/Scripts/customscpt/branch.js"></script>
}